version: "3"

services:
    seedemu-simulator:
        build: .
        container_name: seedemu-simulator:1.0.5
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /tmp/node_info:/tmp/node_info
        ports:
            - 8080:8080
